### ISSUE TITLE
add README

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio-aur#3]
@avbop could you please make a small README.md with:
- a short presentation of what the repository is
- short presentation of the two packages (normal and git)
- how to use the files (directly or through global arch system)
- license (if relevant, otherwise just state Public Domain if you're in America)
- small changelog withe the major changes in these files (not in Gregorio itself)
- the authors
- how to contact, how to bugreport, etc.

Thank you!

**Comment by avbop** [comment]
I might not be able to get to it for a few days, but sure!

**Comment by eroux** [comment]
this is no emergency of course, thank you!

**Comment by avbop** [comment]
I forgot to close this when I updated README.md a while back.
